from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QColor
from PyQt5.QtCore import Qt

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1080, 870)
        Dialog.setMinimumSize(QtCore.QSize(1080, 870))
        Dialog.setMaximumSize(QtCore.QSize(1080, 870))
        self.img_label = QtWidgets.QLabel(Dialog)
        self.img_label.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.img_label.setMinimumSize(QtCore.QSize(1080, 720))
        self.img_label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.img_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.img_label.setLineWidth(1)
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 720, 891, 141))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 871, 81))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.full_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.full_label.setObjectName("full_label")
        self.horizontalLayout_3.addWidget(self.full_label)
        self.full_output = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.full_output.setFont(font)
        self.full_output.setObjectName("full_output")
        self.horizontalLayout_3.addWidget(self.full_output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.empty_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.empty_label.setObjectName("empty_label")
        self.horizontalLayout_4.addWidget(self.empty_label)
        self.empty_output = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.empty_output.setFont(font)
        self.empty_output.setObjectName("empty_output")
        self.horizontalLayout_4.addWidget(self.empty_output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.date_lable = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.date_lable.setObjectName("date_lable")
        self.horizontalLayout.addWidget(self.date_lable)
        self.data_output = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.data_output.setFont(font)
        self.data_output.setObjectName("data_output")
        self.horizontalLayout.addWidget(self.data_output)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.time_lable = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.time_lable.setObjectName("time_lable")
        self.horizontalLayout_2.addWidget(self.time_lable)
        self.time_output = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.time_output.setFont(font)
        self.time_output.setObjectName("time_output")
        self.horizontalLayout_2.addWidget(self.time_output)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(900, 730, 171, 135))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_buttom = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.start_buttom.setCheckable(True)
        self.start_buttom.setAutoExclusive(False)
        self.start_buttom.setObjectName("start_buttom")
        self.verticalLayout_3.addWidget(self.start_buttom)
        self.end_buttom = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.end_buttom.setCheckable(True)
        self.end_buttom.setObjectName("end_buttom")
        self.verticalLayout_3.addWidget(self.end_buttom)
        self.activate_buttom = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.activate_buttom.setCheckable(False)
        self.activate_buttom.setObjectName("activate_buttom")
        self.verticalLayout_3.addWidget(self.activate_buttom)
        self.save_buttom = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.save_buttom.setObjectName("save_buttom")
        self.verticalLayout_3.addWidget(self.save_buttom)
        self.logo_label = QtWidgets.QLabel(Dialog)
        self.logo_label.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.logo_label.setMinimumSize(QtCore.QSize(1080, 720))
        self.logo_label.setStyleSheet("image: url(:/newPrefix/background.png);")
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.logo_label.raise_()
        self.img_label.raise_()
        self.groupBox.raise_()
        self.verticalLayoutWidget_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Information"))
        self.full_label.setText(_translate("Dialog", "Full:"))
        self.full_output.setText(_translate("Dialog", "-"))
        self.empty_label.setText(_translate("Dialog", "Empty :"))
        self.empty_output.setText(_translate("Dialog", "-"))
        self.date_lable.setText(_translate("Dialog", "Date :"))
        self.data_output.setText(_translate("Dialog", "-"))
        self.time_lable.setText(_translate("Dialog", "Time :"))
        self.time_output.setText(_translate("Dialog", "-"))
        self.start_buttom.setText(_translate("Dialog", "Start Video"))
        self.end_buttom.setText(_translate("Dialog", "End Video"))
        self.activate_buttom.setText(_translate("Dialog", "Activate Detection"))
        self.save_buttom.setText(_translate("Dialog", "Save Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
